config/routes.rb
Rails.application.routes.draw do
  root 'application#homepage'

  resources :application, only: [:index]
  resources :albums, :musics, :apis


end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true
  validates :artist, presence: true
  has_many :music, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :album
  belongs_to :musical_genre
end

app/models/musical_genre.rb
class MusicalGenre < ApplicationRecord
  has_many :music
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def create
    album = Album.new(albums_params)
    begin
      album.save!
    rescue => exc
      puts exc
    ensure
      render 'new'
    end
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def show
    @album = Album.find(params[:id])
  end

  def update
    album = Album.find(params[:id])
    begin
      album.update(albums_params)
    rescue ValidationError => exc
      puts exc
      flash[:notice] = "Dados incorretos"
    ensure
      render 'new'
    end
  end

  def destroy
    album = Album.find(params[:id])
    begin
      album.destroy!
    rescue => exc
      puts exc
    ensure
      render 'new'
    end
  end

  private

  def albums_params
    params.require('album').permit(:name, :artist)
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  def index

  end

  def show

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def homepage
    @albums = Album.all
    @musics = Music.all
  end

  def getlink(name)
    last = name.downcase
    @final2 = last.gsub(" ", "-")
    return @final2
  end
  helper_method :getlink

  def show
  end

  end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @musics = Music.all
    @albums = Album.all
    @musical_genres = MusicalGenre.all
  end

  def create
    music = Music.new(music_params)
    begin
      music.save!
    rescue => exc
      puts exc
    ensure
      render 'new'
    end
  end

  def new
    @music = Music.new
    @albums = Album.all
    @musical_genres = MusicalGenre.all
  end

  def edit
    @music = Music.find(params[:id])
    @albums = Album.all
    @musical_genres = MusicalGenre.all
  end

  def show
    @music = Music.find(params[:id])
  end

  def update
    music = Music.find(params[:id])
    begin
      music.update(music_params)
    rescue ValidationError => exc
      puts exc
      flash[:notice] = "Dados incorretos"
    ensure
      render 'index'
    end
  end

  def destroy
    music = Music.find(params[:id])
    @albums = Album.all
    @musical_genres = MusicalGenre.all
    begin
      music.destroy!
    rescue => exc
      puts exc
    ensure
      render 'index'
    end
  end

  private

  def music_params
    params.require('music').permit(:name, :explicit, :album_id, :musical_genre_id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/albums/edit.html.erb
<h1>Editar Album</h1>

<%= form_with model: @album do |form| %>
  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name, value: @album.name  %>
  </div>

  <div class="field">
    <%= form.label :artist, 'Artista' %>
    <%= form.text_field :artist, value: @album.artist %>
  </div>

  <div class="actions">
    <%= form.submit "Atualizar album" %>
  </div>
<% end %>

<%= link_to 'Voltar', albums_path %>

app/views/albums/index.html.erb
<link rel="stylesheet" href="custom.css">
<h1>Albuns salvos</h1>
<p></p>
<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Artista</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.name %></td>
      <td><%= album.artist %></td>
      <td><%= link_to 'Detalhes', album_path(album) %></td>
      <td><%= link_to 'Editar', edit_album_path(album) %></td>
      <td><%= link_to 'Deletar', album_path(album), method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo album', new_album_path %>
<%= link_to 'Home', root_path %>

app/views/albums/new.html.erb
<h1>Novo Album</h1>

<%= form_with model: @album do |form| %>
  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :artist, 'Artista' %>
    <%= form.text_field :artist %>
  </div>

  <div class="actions">
    <%= form.submit "Criar album" %>
  </div>
<% end %>

<%= link_to 'Voltar', albums_path %>

app/views/albums/show.html.erb
<h1>Detalhes do album</h1>

<p>
  <strong>Nome:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Artista:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Adicionado em:</strong>
  <%= @album.created_at %>
</p>

<%= link_to 'Editar', edit_album_path(@album) %>
<%= link_to 'Voltar', albums_path %>

app/views/apis/index.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%=javascript_include_tag 'calendar.js' %>
<% javascript_include_tag "custom" %>
<button id="album_button" type="button" class="btn btn-secondary" onclick="show_button('event_calendar', 'myChart')">Calendario</button>
<button id="album_button" type="button" class="btn btn-secondary" onclick="show_button('myChart', 'event_calendar')">Dados da covid-19</button>
<div id="event_calendar"></div>

<%= javascript_include_tag 'chart.js' %>
<canvas id="myChart"></canvas>

app/views/application/homepage.html.erb
<% javascript_include_tag "custom" %>
<div class="container-fluid">
  <nav class="navbar navbar-light navbar-expand-md bg-faded justify-content-center">
    <a href="#" class="navbar-brand d-flex w-50 mr-auto">Jonas Musics</a>
    <div class="navbar-collapse collapse w-100" id="collapsingNavbar">
      <ul class="navbar-nav w-100 justify-content-end">
        <li class="nav-item">
          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
              <button id="album_button" type="button" class="btn btn-secondary" onclick="show_button('albums', 'musics')">Albuns</button>
              <button id="music_button" type="button" class="btn btn-secondary" onclick="show_button('musics', 'albums')">Musicas</button>
            </div>
        </li>
      </ul>
    </div>
  </nav>
</div>


<p></p>
<div class="page container-fluid albums" id="albums">
<H1> Albuns </H1>
  <div class="row">
  <% @albums.each do |album| %>
      <div class="col-4">
        <div class="card border-dark mb-3" style="width: 20rem;">
          <img src="https://www.vagalume.com.br/<%=getlink(album.artist)%>/discografia/<%=getlink(album.name)%>.webp" class="card-img-top" alt="...">
          <div class="card-body">
            <a href="/albums/<%=album.id%>" style="color: black">
              <h5 id="status_<%=album.name%>" class="card-title"><%= album.name %> </h5>
            </a>
            <h6 class="card-subtitle mb-2 text-muted"><%= album.artist %></h6>
            <p class="card-text"></p>
            <button class="btn" onclick="listened('status_<%=album.name%>')" style="color: gray">
              <i class="fas fa fa-check-circle" title="Escutado"></i>
            </button>
            <button class="btn" onclick="not_listened('status_<%=album.name%>')" style="color: gray">
              <i class="fas fa fa-times" title="Nao escutado"></i>
            </button>
            <button class="btn" onclick="remove('status_<%=album.name%>')" style="color: gray">
              <i class="fas fa fa-ban" title="Remover efeito"></i>
            </button>
          </div>
        </div>
      </div>
    <% end %>
    <div class="col-4">
      <div class="card border-dark mb-3" style="width: 20rem;">
        <img src="https://static.thenounproject.com/png/30444-200.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Novo album</h5>
          <p class="card-text"></p>
          <a href="/albums/new" class="btn btn-success">Adicionar album</a>
        </div>
      </div>
    </div>
    </div>
  </div>

<p></p>

<div class="page container-fluid musics" id="musics">
  <H1> Musicas </H1>
  <% @musics.each do |music| %>
    <div class="list-group">
      <a href="/musics/<%=music.id%>" class="list-group-item list-group-item-action"><%= music.name %> <small class="text-muted"> (<%= music.album.name %>) </small><button class="btn" onclick="like('like_<%=music.id%>')" style="border-radius: 15px"><i id="like_<%=music.id%>" class="fas fa fa-heart"></i></button></a>
    </div>
    <% end %>
  <div class="list-group">
    <a href="/musics/new" class="list-group-item list-group-item-action">Nova musica</a>
  </div>
</div>

app/views/application/index.html.erb
<%=javascript_include_tag 'calendar.js' %>
<div id="event_calendar"></div>

app/views/layouts/application.html.erb
<html>
<!DOCTYPE html>
<head>
    <title>Lista03</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>

    <p id="notice"><%= flash[:notice] %></p
      <%= yield %>
  </body>
</html>

app/views/musics/edit.html.erb
<h1>Editar Musica</h1>

<%= form_with model: @music do |form| %>
  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name, value: @music.name  %>
  </div>

  <div class="field">
    <%= form.label :explicit, 'Explicito' %>
    <%= form.text_field :explicit, value: @music.explicit %>
  </div>

  <div class="field">
    <%= form.label :album_id, 'Álbum' %>
    <%= form.select :album_id, options_for_select(@albums.map { |album| [album.name, album.id] }) %>
  </div>

  <div class="field">
    <%= form.label :musical_genre_id, 'Genero Musical' %>
    <%= form.select :musical_genre_id, options_for_select(@musical_genres.map { |genre| [genre.name, genre.id] }) %>
  </div>

  <div class="actions">
    <%= form.submit "Atualizar musica" %>
  </div>

<% end %>
<%= link_to 'Voltar', musics_path %>

app/views/musics/index.html.erb
<h1>Musicas salvas</h1>

<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Album</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @musics.each do |music| %>
    <tr>
      <td><%= music.name %></td>
      <td><%= music.album.name %></td>
      <td><%= link_to 'Detalhes', music_path(music) %></td>
      <td><%= link_to 'Editar', edit_music_path(music) %></td>
      <td><%= link_to 'Deletar', music_path(music), method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova musica', new_music_path %>
<%= link_to 'Home', root_path %>

app/views/musics/new.html.erb
<h1>Nova Musica</h1>

<%= form_with model: @music do |form| %>
  <div class="field">
    <%= form.label :name, 'Nome' %>
    <br>
    <%= form.text_field :name %>
    <p></p>
  </div>

  <div class="field">
    <%= form.label :explicit, 'Explicito (digite true ou false)' %>
    <br>
    <%= form.text_field :explicit %>
    <p></p>
  </div>

  <div class="field">
    <%= form.label :album_id, 'Album' %>
    <br>
    <%= form.select :album_id, options_for_select(@albums.map { |album| [album.name, album.id] }) %>
    <p></p>
  </div>

  <div class="field">
    <%= form.label :musical_genre_id, 'Genero Musical' %>
    <br>
    <%= form.select :musical_genre_id, options_for_select(@musical_genres.map { |genre| [genre.name, genre.id] }) %>
    <p></p>
  </div>

  <div class="actions">
    <%= form.submit "Criar musica" %>
  </div>
<% end %>

<%= link_to 'Voltar', musics_path %>

app/views/musics/show.html.erb
<h1>Detalhes da musica</h1>

<p>
  <strong>Nome:</strong>
  <%= @music.name %>
</p>

<p>
  <strong>Explicito:</strong>
  <% if (@music.explicit == true); explicit = "Sim"; else explicit = "Nao"; end; %>
    <%= explicit %>
    </p>

<p>
  <strong>Album:</strong>
  <%= @music.album.name %>
</p>

<p>
  <strong>Genero musical:</strong>
  <%= @music.musical_genre.name %>
</p>

<p>
  <strong>Adicionado em:</strong>
  <%= @music.created_at %>
</p>

<%= link_to 'Editar', edit_music_path(@music) %>
<%= link_to 'Voltar', root_path %>